/** @type {import('prettier').Config} */
module.exports = {
  semi: true,
  singleQuote: false,
  printWidth: 100,
  tabWidth: 2,
  trailingComma: "all",
  bracketSpacing: true,
  bracketSameLine: false,
  jsxSingleQuote: false,
  arrowParens: "always",
  useTabs: false,
  endOfLine: "lf",
  importOrder: [
    "^react/(.*)$|^react$",
    "^next/(.*)$|^next$",
    "<BUILTIN_MODULES>",
    "<THIRD_PARTY_MODULES>",
    "<TYPES>",
    "^@/app/types/(.*)$",
    "^@/app/config/(.*)$",
    "^@/app/constants/(.*)$",
    "^@/app/contexts/(.*)$",
    "^@/app/services/(.*)$",
    "^@/app/lib/(.*)$",
    "^@/app/utils/(.*)$",
    "^@/app/hooks/(.*)$",
    "^@/app/components/(.*)$",
    "^@/app/containers/(.*)$",
    "^@/app/sections/(.*)$",
    "^@/app/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderParserPlugins: ["typescript", "jsx"],
  tailwindStylesheet: "./app/globals.css",
  tailwindFunctions: ["clsx", "cn"],
  plugins: ["@trivago/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
};
